#!/bin/sh
# Usage: script/add-secret key=value
# Updates rails secrets through a container.

# Set the RAILS_ENV if not currently set
: ${RAILS_ENV:=development}
export RAILS_ENV
echo ""
echo "Adding $1 secret..."

docker run -it --rm --name changelogger --mount type=bind,source="$(pwd)"/changelogger,target=/data/apps/changelogger changelogger:latest bundle exec rake add_secrets\[$1\]

if [ $? -eq 0 ]; then
  echo "Secret added. Shhh, don't tell anyone."
fi
